lab01 to submit
PdxCodeGuild/class_liger pull request #140
Opened 2022-05-04 04:12 UTC by santorsm

Submitting django lab01

2022-05-14 03:21 UTC, cdmichaelb requested changes
Code Errors on attempting to access server after running.

> FieldError at /
> Cannot resolve keyword 'task_complete' into field. Choices are: completed_date, created_date, id, priority, priority_id, text

2022-05-18 02:34 UTC, cdmichaelb commented
[d32b4ef](https://github.com/PdxCodeGuild/class_liger/pull/140/commits/d32b4efcb4e69427fda286eae2e4586f6151f1ce) corrects issue. Will re-review.

2022-05-18 02:37 UTC, cdmichaelb commented on code/matt/django/lab01/django_to_do/to_do_app/templates/layout/coompleted.html
> +
Typo in this file name, but the file doesn't seem to be used.

2022-05-18 02:42 UTC, cdmichaelb commented on code/matt/django/lab01/django_to_do/to_do_app/views.py
> +def create(request):
Errors if the user attempts to run a GET request on `create` (http://127.0.0.1:8000/create/)

Suggestion: Handle get requests either be returning an error, or returning to index.

2022-05-18 02:44 UTC, cdmichaelb approved these changes
Looks good, all features of the page function properly within the scope of the assignment.

2022-05-20 02:44 UTC, perennialAutodidact commented
Nice work!

A few notes:
1. Watch out for erroneous imports. The most recent versions of VS Code will import things automatically when tab is pressed to auto-complete stuff. I had to remove an unnecessary import from one of the `models.py` files to get the server to start.
2. Model names are written in the singular because they represent the attributes for a single item from the table. (e.g. Priority vs Priorities)

2022-05-20 02:44 UTC, merged