Tyler django lab 1
PdxCodeGuild/class_liger pull request #147
Opened 2022-05-18 02:43 UTC by CardinalKibbles

2022-05-20 02:31 UTC, cdmichaelb requested changes
Please add some more formatting to the page using bootstrap. 


Here are a couple of bootstrap classes you could pull from:

[form-control](https://getbootstrap.com/docs/5.0/forms/form-control/)

[list-group](https://getbootstrap.com/docs/5.0/components/list-group/)

2022-05-30 06:30 UTC, CardinalKibbles commented
I updated the visuals and made it more usable

2022-06-17 01:18 UTC, cdmichaelb approved these changes
Looks much better! Good job.

2022-06-18 01:30 UTC, perennialAutodidact approved these changes

2022-06-18 01:30 UTC, perennialAutodidact commented on code/tyler/django/django_lab-1/todo_app/models.py
> +from django.forms import CharField
Be careful with using `tab` to autocomplete. Recent updates to VSCode will perform automatic imports on things. Lines 1 and 3 are irrelevant in this case

2022-06-18 01:32 UTC, merged